// Generated by scripts/build_site.py — do not edit by hand.
const I18N = {
  "en": {
    "home": "Home",
    "swimTeam": "Swim Team",
    "siteTagline": "Competitive swimmers · Sarajevo, Bosnia & Herzegovina",
    "viewProfile": "View profile →",
    "personalBests": "personal bests",
    "meets": "meets",
    "age": "Age",
    "goalLabel": "Goal",
    "goalsKicker": "Career",
    "goalsTitle": "Goals",
    "pbKicker": "Personal",
    "pbTitle": "Best Times",
    "shortCourse": "Short Course",
    "longCourse": "Long Course",
    "seasonKicker": "Season",
    "progression": "Progression",
    "resultsTitle": "Competition Results",
    "noResults": "No competition results yet.",
    "youthSquad": "Youth Squad",
    "footerSrc": "results sourced from",
    "lastUpdated": "Last updated",
    "spec.ahmed-dzemic": "Distance Freestyle",
    "goal.ahmed-dzemic.0": "D2 college scholarship in the US",
    "goal.ahmed-dzemic.1": "Qualify for the European Junior Championships",
    "goal.ahmed-dzemic.2": "Represent Bosnia & Herzegovina at international championships",
    "goal.ahmed-dzemic.3": "Break 16:00 in the 1500m Freestyle (SCM)",
    "goal.ahmed-dzemic.4": "Break 1:55 in the 200m Freestyle (SCM)"
  },
  "de": {
    "home": "Start",
    "swimTeam": "Schwimmteam",
    "siteTagline": "Leistungsschwimmer · Sarajevo, Bosnien und Herzegowina",
    "viewProfile": "Profil ansehen →",
    "personalBests": "Bestzeiten",
    "meets": "Wettkämpfe",
    "age": "Alter",
    "goalLabel": "Ziel",
    "goalsKicker": "Karriere",
    "goalsTitle": "Ziele",
    "pbKicker": "Persönliche",
    "pbTitle": "Bestzeiten",
    "shortCourse": "Kurzbahn",
    "longCourse": "Langbahn",
    "seasonKicker": "Saison",
    "progression": "Entwicklung",
    "resultsTitle": "Wettkampfergebnisse",
    "noResults": "Noch keine Wettkampfergebnisse.",
    "youthSquad": "Nachwuchskader",
    "footerSrc": "Ergebnisse von",
    "lastUpdated": "Zuletzt aktualisiert",
    "spec.ahmed-dzemic": "Langstrecken-Freistil",
    "goal.ahmed-dzemic.0": "D2-College-Stipendium in den USA",
    "goal.ahmed-dzemic.1": "Qualifikation für die Junioren-Europameisterschaft",
    "goal.ahmed-dzemic.2": "Bosnien und Herzegowina bei internationalen Meisterschaften vertreten",
    "goal.ahmed-dzemic.3": "Unter 16:00 über 1500m Freistil (Kurzbahn)",
    "goal.ahmed-dzemic.4": "Unter 1:55 über 200m Freistil (Kurzbahn)"
  },
  "bs": {
    "home": "Početna",
    "swimTeam": "Plivački tim",
    "siteTagline": "Takmičarski plivači · Sarajevo, Bosna i Hercegovina",
    "viewProfile": "Pogledaj profil →",
    "personalBests": "ličnih rekorda",
    "meets": "takmičenja",
    "age": "Godine",
    "goalLabel": "Cilj",
    "goalsKicker": "Karijera",
    "goalsTitle": "Ciljevi",
    "pbKicker": "Lični",
    "pbTitle": "Rekordi",
    "shortCourse": "Mali bazen",
    "longCourse": "Veliki bazen",
    "seasonKicker": "Sezona",
    "progression": "Napredak",
    "resultsTitle": "Rezultati takmičenja",
    "noResults": "Još nema rezultata takmičenja.",
    "youthSquad": "Mlađe kategorije",
    "footerSrc": "rezultati sa",
    "lastUpdated": "Posljednje ažurirano",
    "spec.ahmed-dzemic": "Slobodni stil — duge pruge",
    "goal.ahmed-dzemic.0": "D2 univerzitetska stipendija u SAD-u",
    "goal.ahmed-dzemic.1": "Kvalifikacija za Evropsko juniorsko prvenstvo",
    "goal.ahmed-dzemic.2": "Nastupati za reprezentaciju BiH na međunarodnim prvenstvima",
    "goal.ahmed-dzemic.3": "Isplivati ispod 16:00 na 1500m slobodno (SCM)",
    "goal.ahmed-dzemic.4": "Isplivati ispod 1:55 na 200m slobodno (SCM)"
  }
};

function applyLang(lang) {
  if (!I18N[lang]) lang = "en";
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const text = I18N[lang][el.dataset.i18n];
    if (text) el.textContent = text;
  });
  document.querySelectorAll(".lang-switch button").forEach((btn) => {
    btn.classList.toggle("active", btn.dataset.lang === lang);
  });
  try { localStorage.setItem("lang", lang); } catch (e) {}
}

document.addEventListener("DOMContentLoaded", () => {
  document.querySelectorAll(".lang-switch button").forEach((btn) => {
    btn.addEventListener("click", () => applyLang(btn.dataset.lang));
  });
  let saved = "en";
  try { saved = localStorage.getItem("lang") || "en"; } catch (e) {}
  applyLang(saved);
});
