// Generated by scripts/build_site.py — do not edit by hand.
const I18N = {
  "en": {
    "home": "Home",
    "swimTeam": "Swim Team",
    "siteTagline": "Competitive swimmers · Sarajevo, Bosnia & Herzegovina",
    "viewProfile": "View profile →",
    "personalBests": "personal bests",
    "meets": "meets",
    "age": "Age",
    "goalLabel": "Goal",
    "goalsKicker": "Career",
    "goalsTitle": "Goals",
    "pbKicker": "Personal",
    "pbTitle": "Best Times",
    "shortCourse": "Short Course",
    "longCourse": "Long Course",
    "seasonKicker": "Season",
    "progression": "Progression",
    "resultsTitle": "Competition Results",
    "noResults": "No competition results yet.",
    "youthSquad": "Youth Squad",
    "footerSrc": "results sourced from",
    "lastUpdated": "Last updated",
    "recruitingKicker": "Recruiting",
    "recruitingTitle": "Contact",
    "recruitingIntro": "Available for college recruiting inquiries.",
    "availableFrom": "Available from",
    "eligibility": "Eligibility",
    "headCoach": "Head Coach",
    "contactAthlete": "Email athlete",
    "contactCoach": "Email coach",
    "spec.ahmed-dzemic": "Distance Freestyle",
    "goal.ahmed-dzemic.0": "D2 college scholarship in the US (D1 as stretch goal)",
    "goal.ahmed-dzemic.1": "Complete NCAA eligibility, SAT & TOEFL by 2027",
    "goal.ahmed-dzemic.2": "Senior national champion of BiH in the 400/800/1500 Freestyle",
    "goal.ahmed-dzemic.3": "Medal at the Balkan Championships",
    "goal.ahmed-dzemic.4": "Represent BiH at the European Junior Championships",
    "goal.ahmed-dzemic.5": "Break 1:55 in the 200m Freestyle (SCM)",
    "goal.ahmed-dzemic.6": "Break 4:05 in the 400m Freestyle (LCM)",
    "goal.ahmed-dzemic.7": "National record of BiH in the 800m or 1500m Freestyle"
  },
  "de": {
    "home": "Start",
    "swimTeam": "Schwimmteam",
    "siteTagline": "Leistungsschwimmer · Sarajevo, Bosnien und Herzegowina",
    "viewProfile": "Profil ansehen →",
    "personalBests": "Bestzeiten",
    "meets": "Wettkämpfe",
    "age": "Alter",
    "goalLabel": "Ziel",
    "goalsKicker": "Karriere",
    "goalsTitle": "Ziele",
    "pbKicker": "Persönliche",
    "pbTitle": "Bestzeiten",
    "shortCourse": "Kurzbahn",
    "longCourse": "Langbahn",
    "seasonKicker": "Saison",
    "progression": "Entwicklung",
    "resultsTitle": "Wettkampfergebnisse",
    "noResults": "Noch keine Wettkampfergebnisse.",
    "youthSquad": "Nachwuchskader",
    "footerSrc": "Ergebnisse von",
    "lastUpdated": "Zuletzt aktualisiert",
    "recruitingKicker": "Recruiting",
    "recruitingTitle": "Kontakt",
    "recruitingIntro": "Offen für Anfragen von College-Trainern.",
    "availableFrom": "Verfügbar ab",
    "eligibility": "Nationalität",
    "headCoach": "Cheftrainer",
    "contactAthlete": "Athlet kontaktieren",
    "contactCoach": "Trainer kontaktieren",
    "spec.ahmed-dzemic": "Langstrecken-Freistil",
    "goal.ahmed-dzemic.0": "D2-College-Stipendium in den USA (D1 als ambitioniertes Ziel)",
    "goal.ahmed-dzemic.1": "NCAA-Zulassung, SAT & TOEFL bis 2027 abschließen",
    "goal.ahmed-dzemic.2": "Bosnischer Meister über 400/800/1500 Freistil (Senioren)",
    "goal.ahmed-dzemic.3": "Medaille bei den Balkan-Meisterschaften",
    "goal.ahmed-dzemic.4": "BiH bei der Junioren-Europameisterschaft vertreten",
    "goal.ahmed-dzemic.5": "Unter 1:55 über 200m Freistil (Kurzbahn)",
    "goal.ahmed-dzemic.6": "Unter 4:05 über 400m Freistil (Langbahn)",
    "goal.ahmed-dzemic.7": "Landesrekord von BiH über 800m oder 1500m Freistil"
  },
  "bs": {
    "home": "Početna",
    "swimTeam": "Plivački tim",
    "siteTagline": "Takmičarski plivači · Sarajevo, Bosna i Hercegovina",
    "viewProfile": "Pogledaj profil →",
    "personalBests": "ličnih rekorda",
    "meets": "takmičenja",
    "age": "Godine",
    "goalLabel": "Cilj",
    "goalsKicker": "Karijera",
    "goalsTitle": "Ciljevi",
    "pbKicker": "Lični",
    "pbTitle": "Rekordi",
    "shortCourse": "Mali bazen",
    "longCourse": "Veliki bazen",
    "seasonKicker": "Sezona",
    "progression": "Napredak",
    "resultsTitle": "Rezultati takmičenja",
    "noResults": "Još nema rezultata takmičenja.",
    "youthSquad": "Mlađe kategorije",
    "footerSrc": "rezultati sa",
    "lastUpdated": "Posljednje ažurirano",
    "recruitingKicker": "Kontakt za trenere",
    "recruitingTitle": "Kontakt",
    "recruitingIntro": "Dostupan za upite college trenera.",
    "availableFrom": "Dostupan od",
    "eligibility": "Nacionalnost",
    "headCoach": "Glavni trener",
    "contactAthlete": "Kontaktiraj plivača",
    "contactCoach": "Kontaktiraj trenera",
    "spec.ahmed-dzemic": "Slobodni stil — duge pruge",
    "goal.ahmed-dzemic.0": "D2 univerzitetska stipendija u SAD-u (D1 kao viši cilj)",
    "goal.ahmed-dzemic.1": "Završiti NCAA registraciju, SAT i TOEFL do 2027.",
    "goal.ahmed-dzemic.2": "Seniorski prvak BiH na 400/800/1500 slobodno",
    "goal.ahmed-dzemic.3": "Medalja na Balkanskom prvenstvu",
    "goal.ahmed-dzemic.4": "Predstavljati BiH na Evropskom juniorskom prvenstvu",
    "goal.ahmed-dzemic.5": "Isplivati ispod 1:55 na 200m slobodno (SCM)",
    "goal.ahmed-dzemic.6": "Isplivati ispod 4:05 na 400m slobodno (LCM)",
    "goal.ahmed-dzemic.7": "Državni rekord BiH na 800m ili 1500m slobodno"
  }
};

function applyLang(lang) {
  if (!I18N[lang]) lang = "en";
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const text = I18N[lang][el.dataset.i18n];
    if (text) el.textContent = text;
  });
  document.querySelectorAll(".lang-switch button").forEach((btn) => {
    btn.classList.toggle("active", btn.dataset.lang === lang);
  });
  try { localStorage.setItem("lang", lang); } catch (e) {}
}

document.addEventListener("DOMContentLoaded", () => {
  document.querySelectorAll(".lang-switch button").forEach((btn) => {
    btn.addEventListener("click", () => applyLang(btn.dataset.lang));
  });
  let saved = "en";
  try { saved = localStorage.getItem("lang") || "en"; } catch (e) {}
  applyLang(saved);
});
